#!/usr/bin/env python
import sys, os
arguments = ' '.join(sys.argv[1:])
arguments = [] if not arguments else ["--arguments", arguments]
os.execvp("phoenix", ["phoenix", "runhook", "--hook", "pre-applypatch", "--repository-id", "$repo"] + arguments)